name: complyance-publish
on:
  workflow_dispatch:
    inputs:
      postgresVersion:
        description: "Postgres Major version"
        required: true
        default: "14"
      pgvectorVersion:
        description: "Pgvector version"
        required: true
        default: "v0.5.1"

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.pgvectorVersion }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push pgvector image to container registry
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            PG_MAJOR=${{ inputs.postgresVersion }}
          tags: |
            ghcr.io/complyance/pgvector:${{ inputs.pgvectorVersion }}
